[package]

name = "LambdaOxide"
version = "0.1.10"
authors = [ "Konstantin Kowalski <kostelkow@gmail.com>" ]

[dependencies]
time = "0.1.35"

[lib]
name = "lambda_oxide"
path = "src/lib.rs"

[[bin]]
name = "lorepl"
path = "src/bin.rs"
