[package]

name = "LambdaOxide"
version = "0.1.6"
authors = [ "Konstantin Kowalski <kostelkow@gmail.com>" ]

[lib]
name = "lambda_oxide"
path = "src/lib.rs"

[[bin]]
name = "lorepl"
path = "src/bin.rs"
