[package]

name = "lopiper"
version = "0.0.2"
authors = [ "Konstantin Kowalski <kostelkow@gmail.com>" ]

[dependencies]
OxiCloak = { git = "https://github.com/KostyaKow/OxiCloak.git", version = "0.0.1" }
